import type { Database } from "@/types/database";

/**
 * Application-facing aliases for the generated database types.
 *
 * Everything here is *derived* from `@/types/database`, which is generated by
 * `npm run db:types`. Nothing in this file restates the schema, so the two
 * cannot drift — if a column changes, this stops compiling.
 */

export type UserRole = Database["public"]["Enums"]["user_role"];

export type Profile = Database["public"]["Tables"]["profiles"]["Row"];
export type ProfileUpdate = Database["public"]["Tables"]["profiles"]["Update"];

export const USER_ROLES = ["USER", "AGENT", "ADMIN"] as const satisfies readonly UserRole[];
