import type { Database } from "@/types/database";

/**
 * Application-facing aliases for the generated database types.
 *
 * Everything here is *derived* from `@/types/database`, which is generated by
 * `npm run db:types`. Nothing in this file restates the schema, so the two
 * cannot drift — if a column changes, this stops compiling.
 */

export type UserRole = Database["public"]["Enums"]["user_role"];

export type Profile = Database["public"]["Tables"]["profiles"]["Row"];
export type ProfileUpdate = Database["public"]["Tables"]["profiles"]["Update"];

export const USER_ROLES = ["USER", "AGENT", "ADMIN"] as const satisfies readonly UserRole[];

// --- Phase 2: tickets --------------------------------------------------------

export type TicketStatus = Database["public"]["Enums"]["ticket_status"];
export type TicketPriority = Database["public"]["Enums"]["ticket_priority"];

export type Ticket = Database["public"]["Tables"]["tickets"]["Row"];
export type TicketInsert = Database["public"]["Tables"]["tickets"]["Insert"];
export type Category = Database["public"]["Tables"]["categories"]["Row"];
export type Project = Database["public"]["Tables"]["projects"]["Row"];
export type ProjectRole = Database["public"]["Enums"]["project_role"];
export type ProjectMember =
  Database["public"]["Tables"]["project_members"]["Row"];

export const PROJECT_ROLES = [
  "VIEWER",
  "MEMBER",
  "AGENT",
  "MANAGER",
] as const satisfies readonly ProjectRole[];

/** A project member joined with the profile shown alongside them. */
export type ProjectMemberWithProfile = ProjectMember & {
  profile: Pick<Profile, "id" | "full_name" | "email" | "avatar_url"> | null;
  /**
   * Who added them, since 0022. Null for memberships that predate it, and for
   * anyone added by the service role — "unknown" rather than a guess.
   */
  adder?: Pick<Profile, "id" | "full_name" | "email" | "avatar_url"> | null;
};

/**
 * Who is acting, within one project.
 *
 * Ticket permissions depend on the project role, not the global one, so
 * components take this rather than a bare Profile. Computed once on the server
 * and passed down.
 */
export type TicketActor = {
  id: string;
  /** Global ADMIN: superuser across every project. */
  isSystemAdmin: boolean;
  /** Null when not a member — only reachable as a system admin. */
  projectRole: ProjectRole | null;
};

export const TICKET_STATUSES = [
  "OPEN",
  "IN_PROGRESS",
  "PENDING",
  "RESOLVED",
  "CLOSED",
] as const satisfies readonly TicketStatus[];

export const TICKET_PRIORITIES = [
  "LOW",
  "MEDIUM",
  "HIGH",
  "URGENT",
] as const satisfies readonly TicketPriority[];

/** Someone a ticket is assigned to. */
export type TicketAssignee = Pick<
  Profile,
  "id" | "full_name" | "email" | "avatar_url"
>;

/**
 * A ticket joined with the names it is displayed alongside.
 *
 * `assignees` is a list, and an empty list is what "unassigned" means — there
 * is no null assignee any more. `assignee_count` on the ticket itself mirrors
 * `assignees.length`; it exists so the list query can filter and sort on it
 * without joining, and the database keeps the two in step.
 */
export type TicketWithRelations = Ticket & {
  project: Pick<Project, "id" | "key" | "name"> | null;
  category: Pick<Category, "id" | "name"> | null;
  creator: Pick<Profile, "id" | "full_name" | "email" | "avatar_url"> | null;
  assignees: TicketAssignee[];
};

/** The planning dates, kept together since they are always edited as a pair. */
export type TicketSchedule = Pick<Ticket, "start_date" | "end_date">;

// --- Notifications -----------------------------------------------------------

export type NotificationType = Database["public"]["Enums"]["notification_type"];
export type Notification = Database["public"]["Tables"]["notifications"]["Row"];

/**
 * A notification joined with the ticket it refers to and whoever caused it.
 *
 * Both are nullable: `actor_id` is nulled when that profile is deleted, and the
 * ticket embed can come back null if RLS hides it — a notification outliving
 * the caller's access to its ticket is possible after a role change.
 */
export type NotificationWithContext = Notification & {
  ticket: Pick<Ticket, "id" | "ticket_number" | "title"> | null;
  actor: Pick<Profile, "id" | "full_name" | "email" | "avatar_url"> | null;
};
