import type { Database } from "@/types/database";

/**
 * Application-facing aliases for the generated database types.
 *
 * Everything here is *derived* from `@/types/database`, which is generated by
 * `npm run db:types`. Nothing in this file restates the schema, so the two
 * cannot drift — if a column changes, this stops compiling.
 */

export type UserRole = Database["public"]["Enums"]["user_role"];

export type Profile = Database["public"]["Tables"]["profiles"]["Row"];
export type ProfileUpdate = Database["public"]["Tables"]["profiles"]["Update"];

export const USER_ROLES = ["USER", "AGENT", "ADMIN"] as const satisfies readonly UserRole[];

// --- Phase 2: tickets --------------------------------------------------------

export type TicketStatus = Database["public"]["Enums"]["ticket_status"];
export type TicketPriority = Database["public"]["Enums"]["ticket_priority"];

export type Ticket = Database["public"]["Tables"]["tickets"]["Row"];
export type TicketInsert = Database["public"]["Tables"]["tickets"]["Insert"];
export type Category = Database["public"]["Tables"]["categories"]["Row"];
export type Project = Database["public"]["Tables"]["projects"]["Row"];

export const TICKET_STATUSES = [
  "OPEN",
  "IN_PROGRESS",
  "PENDING",
  "RESOLVED",
  "CLOSED",
] as const satisfies readonly TicketStatus[];

export const TICKET_PRIORITIES = [
  "LOW",
  "MEDIUM",
  "HIGH",
  "URGENT",
] as const satisfies readonly TicketPriority[];

/** A ticket joined with the names it is displayed alongside. */
export type TicketWithRelations = Ticket & {
  project: Pick<Project, "id" | "key" | "name"> | null;
  category: Pick<Category, "id" | "name"> | null;
  creator: Pick<Profile, "id" | "full_name" | "email" | "avatar_url"> | null;
  assignee: Pick<Profile, "id" | "full_name" | "email" | "avatar_url"> | null;
};

/** The planning dates, kept together since they are always edited as a pair. */
export type TicketSchedule = Pick<Ticket, "start_date" | "end_date">;
